# Change these first
owner: jerryyang-git # Your GitHub organization or username, where this repository lives
repo: Site-operation-detection # The name of this repository

sites:
  - name: 👋小忧忧のBlog
    url: https://www.jerryyang.link
  - name: ImgIO 图床
    url: https://imgio.jerryyang.link
  - name: meowfacts 猫知识 API
    url: https://meowfacts.jerryyang.link
  - name: Vaultwarden By Youyou
    url: https://vault.jerryyang.link/
  - name: 七米蓝
    url: https://chirmyram.top
  - name: XZH的博客
    url: https://blog.xzh.gs
  - name: 梓澪のBlog
    url: https://zil.ing
  - name: 紫缘社
    url: https://galzy.eu.org
  - name: 紫缘社Dlink
    url: https://dlinkline.transmission2.eu.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: runtime.jerryyang.link
  # baseUrl: /your-repo-name
  logoUrl: https://img.jerryyang.link/2023/07/08/4.webp
  name: Upptime By Youyou
  introTitle: "**相关站点运行状态"
  introMessage: "这里是Youyou的相关站点运行状态"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
